dist: trusty
# Work-around for https://github.com/travis-ci/travis-ci/issues/8836.
sudo: required
language: node_js
node_js:
  - 8

script:
  - npm run test:lint
  - npm run test:build
  - npm run test:coverage
  - npm run test:browser

after_success:
  - cat coverage/lcov.info | coveralls
